backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - label: 'Actualités'
    name: 'actualite'
    folder: 'content/actualites-agenda'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Date de publication', name: 'publishDate', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Catégories', name: 'categories', widget: 'select', options: ["municipalité", "intercommunalité", "vie culturelle"] }
      - { label: 'Mots-clés', name: 'tags', widget: 'list' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Accueil"
        name: "home"
        file: "site/content/_index.yml"
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Contenu', name: 'body', widget: 'markdown' }
      - label: "Accès directs"
        name: "acces-directs"
        file: "site/content/acces-directs.yml"
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Date', name: 'date', widget: 'datetime' }
          - { label: 'Description', name: 'description', widget: 'string' }
          - { label: 'Sous-titre', name: 'subtitle', widget: 'string' }
          - { label: 'Contenu', name: 'body', widget: 'markdown' }
